[package]
name = "plume"
type = "lib"
authors = ["Distributed Lab"]
license = "MIT"
description = "PLUME implementation in Noir."
compiler_version = ">=0.36.0"

[dependencies]
noir_bigcurve = { tag = "v0.9.0", git = "https://github.com/noir-lang/noir_bigcurve" }
bignum = { tag = "v0.7.3", git = "https://github.com/noir-lang/noir-bignum" }
nodash = { tag = "v0.40.2", git = "https://github.com/olehmisar/nodash" }
ec = { tag = "v0.1.2", git = "https://github.com/noir-lang/ec" }
